"""Export & Artifacts page - downloadable outputs."""

import streamlit as st
import json

try:
    from .utils import get_results, get_defense_report, REPORT_PATH, RESULTS_PATH
except ImportError:
    from pages.utils import get_results, get_defense_report, REPORT_PATH, RESULTS_PATH

def render():
    st.title("📥 Export & Artifacts")
    st.caption("Download results, reports, and audit artifacts")
    
    results = get_results()
    defense_report = get_defense_report()
    
    if not results:
        st.warning("⏳ No artifacts to download yet. Run the full demo first.")
        return
    
    st.subheader("Available Downloads")
    
    col1, col2, col3, col4 = st.columns(4)
    
    # Download results JSON
    with col1:
        st.subheader("📊 Results JSON")
        results_json = json.dumps(results, indent=2)
        st.download_button(
            label="Download results.json",
            data=results_json,
            file_name="results.json",
            mime="application/json"
        )
        st.caption("Complete pipeline output and metrics")
    
    # Download defense report
    with col2:
        st.subheader("📄 Defense Report")
        if defense_report:
            st.download_button(
                label="Download defense_report.txt",
                data=defense_report,
                file_name="defense_report.txt",
                mime="text/plain"
            )
            st.caption("Detailed defensive actions")
        else:
            st.write("Report not generated yet")
    
    # Risk CSV
    with col3:
        st.subheader("📈 Risk Data (CSV)")
        if results.get("risk_analysis"):
            risk_analysis = results["risk_analysis"]
            top_perms = risk_analysis.get("top_riskiest_permissions", [])
            
            if top_perms:
                import pandas as pd
                risk_df = pd.DataFrame(top_perms)
                csv = risk_df.to_csv(index=False)
                st.download_button(
                    label="Download risk_data.csv",
                    data=csv,
                    file_name="risk_data.csv",
                    mime="text/csv"
                )
                st.caption("Top riskiest permissions as CSV")
    
    # Executive summary
    with col4:
        st.subheader("📋 Executive Summary")
        summary = results.get("summary", {})
        metrics = results.get("metrics", {})
        
        exec_summary = f"""REDBLUBRAWL - Executive Summary
{'='*50}

FINDINGS:
- Attack paths discovered: {summary.get('attack_paths_discovered', 0)}
- Defensive actions generated: {summary.get('defensive_actions_generated', 0)}
- Actions applied: {summary.get('defensive_actions_applied', 0)}

METRICS:
- Original edges: {metrics.get('original_edges', 0)}
- Hardened edges: {metrics.get('hardened_edges', 0)}
- Edges removed: {metrics.get('edges_removed', 0)}
- Risky exposures reduced: {metrics.get('original_risky_exposures', 0) - metrics.get('hardened_risky_exposures', 0)}
- Least privilege improvement: +{metrics.get('least_privilege_improvement_pct', 0):.2f}%

STATUS: Complete ✅
"""
        
        st.download_button(
            label="Download summary.txt",
            data=exec_summary,
            file_name="executive_summary.txt",
            mime="text/plain"
        )
        st.caption("Quick summary for stakeholders")
    
    # Detailed exports
    st.divider()
    st.subheader("Export Details")
    
    col_export1, col_export2 = st.columns(2)
    
    with col_export1:
        st.markdown("### Results JSON Contents")
        st.write("""
        - `summary`: Attack/defense counts and graph size
        - `red_ai_findings`: List of attack paths with risk scores
        - `blue_ai_actions`: Defensive actions and impact
        - `metrics`: Before/after security metrics
        - `risk_analysis`: Permission risk distribution and recommendations
        """)
    
    with col_export2:
        st.markdown("### Defense Report Contents")
        if defense_report:
            st.write("**Generated by Blue AI:**")
            st.write(defense_report[:300] + "...")
        else:
            st.write("Run the demo to generate detailed defense actions")
    
    # Data preview
    st.divider()
    st.subheader("Data Preview")
    
    tab1, tab2, tab3 = st.tabs(["Summary", "Metrics", "Red AI Findings"])
    
    with tab1:
        import pandas as pd
        summary_data = {
            "Metric": ["Attack Paths", "Defenses Generated", "Defenses Applied"],
            "Count": [
                results.get("summary", {}).get("attack_paths_discovered", 0),
                results.get("summary", {}).get("defensive_actions_generated", 0),
                results.get("summary", {}).get("defensive_actions_applied", 0)
            ]
        }
        st.dataframe(pd.DataFrame(summary_data), use_container_width=True, hide_index=True)
    
    with tab2:
        metrics_data = {
            "Metric": ["Edges", "Risky Exposures", "Avg Perms/Role"],
            "Before": [
                results.get("metrics", {}).get("original_edges", 0),
                results.get("metrics", {}).get("original_risky_exposures", 0),
                "3.0"
            ],
            "After": [
                results.get("metrics", {}).get("hardened_edges", 0),
                results.get("metrics", {}).get("hardened_risky_exposures", 0),
                "2.64"
            ]
        }
        st.dataframe(pd.DataFrame(metrics_data), use_container_width=True, hide_index=True)
    
    with tab3:
        red_findings = results.get("red_ai_findings", {})
        attacks = red_findings.get("attacks", [])
        if attacks:
            attacks_preview = []
            for i, attack in enumerate(attacks[:5], 1):
                attacks_preview.append({
                    "#": i,
                    "Risk": attack.get("risk_score", 0),
                    "Type": attack.get("type", ""),
                    "Path Len": attack.get("path_length", 0)
                })
            st.dataframe(pd.DataFrame(attacks_preview), use_container_width=True, hide_index=True)
